"""
OpenAI Codex Adapter — generates AGENTS.md (hooks not supported)

AGENTS.md structure:
  [project header — written once on first create, never touched again]

  <!-- amk:start -->
  <!-- GENERATED by agent-memory-kit. DO NOT EDIT MANAGED BLOCK DIRECTLY. -->
  [managed memory protocol + architecture ref + conventions]
  <!-- amk:end -->

  [custom content outside sentinels is preserved across regenerations]

Note: Hermes also reads AGENTS.md. The hermes adapter produces a superset
(with skills note + memory mirroring footer). If you use both Codex and Hermes,
run the hermes adapter (or `generate.py all`, which runs codex then hermes so
hermes wins).
"""
from pathlib import Path

from .utils import write_managed_section, check_managed_section


_MANAGED_TEMPLATE = """\
## Memory System

This project uses a file-based memory system to maintain context across sessions.

### On Session Start

Read `memory/semantic.md` ONCE to load project context before answering.

### On Every Turn

The preprompt hook handles reading `memory/working.md`.

### Task Files

Only load `/dev/[task]/*` files when actively working on that task.

### MCP Efficiency

Before calling any MCP tool to retrieve information, first check if that information might exist in `memory/semantic.md` or `dev/[task]/context.md` — local files are cheaper than remote MCP queries.

### Keep Context Minimal

Do not speculatively load files "just in case".

### Mid-Session Drift

If reasoning becomes uncertain or inconsistent with prior context, re-read `memory/semantic.md` before continuing.

### Memory Discipline

- `memory/semantic.md` — current build state; propose updates; wait for approval before writing
- `memory/working.md` — live task state; update freely after each response; no approval needed
- `DECISIONS.md` — append-only log of architectural decisions; propose entries for approval
- `{arch_file}` — principles, load-bearing assumptions, planned capabilities; update only on merge when a capability ships or an assumption is invalidated; **never put current state here** (that's `semantic.md`), **never put planning details here** (tickets, checklists, phases)
- `dev/[task]/context.md` — log confirmed assumptions immediately; no approval needed

**DECISIONS.md vs. Assumptions distinction:**
- `DECISIONS.md` = immutable log — "we chose X on date Y because Z" — never edited, only superseded by appending
- `{arch_file}` Assumptions = live load-bearing premises — mutable; when invalidated, append a supersession to `DECISIONS.md` first, then update the assumption

**On PR merge:** check `{arch_file}` — move shipped capabilities to `memory/semantic.md` and remove them from the Vision section; append a supersession to `DECISIONS.md` then update or remove any invalidated Assumption.

---

## Architecture

Before implementing a feature, read `{arch_file}`. It is the canonical record of architectural principles, load-bearing assumptions, and planned capabilities — not current build state (that lives in `memory/semantic.md`).

---

## Key conventions

{conventions_md}
"""


def _build_managed_content(config: dict) -> str:
    """Build the managed-section content from config."""
    arch_file = config.get("architecture", {}).get("file", "vision.md")
    conventions = config.get("conventions", [])
    conventions_md = (
        "\n".join(f"- {c}" for c in conventions) if conventions else ""
    )
    return _MANAGED_TEMPLATE.format(
        arch_file=arch_file,
        conventions_md=conventions_md,
    )


def generate(project_root: Path, config: dict) -> str:
    project = config["project"]
    managed_content = _build_managed_content(config)
    header = (
        f"# Project Context — {project['name']}\n\n"
        f"**{project['name']}** is {project['description']}"
    )

    agents_md_status = write_managed_section(
        project_root / "AGENTS.md", header, managed_content, "AGENTS.md"
    )

    return (
        "Codex configuration generated:\n"
        f"{agents_md_status}\n\n"
        "Note: Codex does not support hooks. Memory loading relies on the agent reading AGENTS.md at session start.\n"
        "Note: If you also use Hermes, run `generate.py hermes` instead — the hermes AGENTS.md is a superset.\n"
        "  Custom content outside <!-- amk:start/end --> is preserved."
    )


# ── Check mode ────────────────────────────────────────────────────────────────


def check(project_root: Path, config: dict) -> list[str]:
    """Return drift diffs for all managed files (empty if no drift)."""
    managed_content = _build_managed_content(config)
    result = check_managed_section(
        project_root / "AGENTS.md", managed_content, "AGENTS.md (codex)"
    )
    return [result] if result else []
