"""Shared adapter utilities."""
import difflib
from pathlib import Path
from typing import Optional


# ── Sentinels ─────────────────────────────────────────────────────────────────

SENTINEL_START = "<!-- amk:start -->"
SENTINEL_END = "<!-- amk:end -->"

# ── Generated banners (per file type) ─────────────────────────────────────────

GENERATED_BANNER_MD = (
    "<!-- GENERATED by agent-memory-kit. DO NOT EDIT MANAGED BLOCK DIRECTLY. -->"
)
GENERATED_BANNER_SH = "# Generated by agent-memory-kit. Do not edit directly."


# ── Gitignore ─────────────────────────────────────────────────────────────────

def ensure_gitignored(project_root: Path, entry: str) -> None:
    """Add entry to project .gitignore if not already present."""
    gitignore_path = project_root / ".gitignore"
    if gitignore_path.exists():
        content = gitignore_path.read_text()
        if entry in content.splitlines():
            return
        if not content.endswith("\n"):
            content += "\n"
        gitignore_path.write_text(content + entry + "\n")
    else:
        gitignore_path.write_text(entry + "\n")


# ── Managed-section (sentinel-based) write ────────────────────────────────────


def write_managed_section(
    file_path: Path,
    header: str,
    content: str,
    label: str,
    frontmatter: str = "",
) -> str:
    """Insert or replace an amk-managed block in a file.

    On first create: writes header (outside sentinel) + managed block.
    On re-run with sentinels present: replaces only the managed block.
    On file exists but no sentinels: appends the managed block.

    If *frontmatter* is provided (e.g. YAML frontmatter for Cursor rules),
    it is written once on first create and never touched again.

    Returns a human-readable status line.
    """
    banner_line = GENERATED_BANNER_MD + "\n"
    block = f"{SENTINEL_START}\n{banner_line}{content.rstrip()}\n{SENTINEL_END}\n"

    if not file_path.exists():
        body = f"{header}\n\n{block}" if not frontmatter else f"{frontmatter}\n{header}\n\n{block}"
        file_path.write_text(body)
        return f"  - {label} (created)"

    existing = file_path.read_text()
    start_idx = existing.find(SENTINEL_START)
    end_idx = existing.find(SENTINEL_END)

    if start_idx == -1 or end_idx == -1 or end_idx < start_idx:
        sep = "\n" if existing.endswith("\n") else "\n\n"
        file_path.write_text(existing + sep + block)
        return f"  - {label} (amk section appended — existing content preserved)"

    old_block = existing[start_idx : end_idx + len(SENTINEL_END)]
    new_block = block.rstrip("\n")

    if old_block == new_block:
        return f"  - {label} (unchanged)"

    updated = existing[:start_idx] + block + existing[end_idx + len(SENTINEL_END) :]
    file_path.write_text(updated)

    diff_lines = list(
        difflib.unified_diff(
            old_block.splitlines(keepends=True),
            new_block.splitlines(keepends=True),
            fromfile=f"{label} (before)",
            tofile=f"{label} (after)",
        )
    )
    return f"  - {label} (amk section updated)\n{''.join(diff_lines)}"


# ── Managed-section check (for --check) ───────────────────────────────────────


def check_managed_section(
    file_path: Path,
    expected_content: str,
    label: str,
) -> Optional[str]:
    """Check if a sentinel-managed file's managed block matches expected content.

    Returns None if the block matches (or file doesn't exist yet).
    Returns a unified diff string on mismatch.
    """
    if not file_path.exists():
        return f"{label}: file does not exist (not yet generated)"

    existing = file_path.read_text()
    start_idx = existing.find(SENTINEL_START)
    end_idx = existing.find(SENTINEL_END)

    if start_idx == -1 or end_idx == -1 or end_idx < start_idx:
        # No sentinel block — report the full file as needing generation
        return f"{label}: no managed block found (file needs initial generation)"

    banner_line = GENERATED_BANNER_MD + "\n"
    expected_block = f"{SENTINEL_START}\n{banner_line}{expected_content.rstrip()}\n{SENTINEL_END}"

    actual_block = existing[start_idx : end_idx + len(SENTINEL_END)]

    if actual_block == expected_block:
        return None

    diff_lines = list(
        difflib.unified_diff(
            actual_block.splitlines(keepends=True),
            expected_block.splitlines(keepends=True),
            fromfile=f"{label} (actual)",
            tofile=f"{label} (expected)",
        )
    )
    return "".join(diff_lines)


def check_fully_generated(
    file_path: Path,
    expected_content: str,
    label: str,
) -> Optional[str]:
    """Check if a fully-generated file matches expected content.

    Returns None if it matches (or file doesn't exist yet).
    Returns a unified diff string on mismatch.
    """
    if not file_path.exists():
        return f"{label}: file does not exist (not yet generated)"

    actual = file_path.read_text()
    if actual == expected_content:
        return None

    diff_lines = list(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected_content.splitlines(keepends=True),
            fromfile=f"{label} (actual)",
            tofile=f"{label} (expected)",
        )
    )
    return "".join(diff_lines)
